version: "3"

services:
  api:
    container_name: github_actions_nest
    build:
      context: ./nest
      dockerfile: Dockerfile.prod
    volumes:
      - "./nest:/nest"
    tty: true
    ports:
      - 3000:3000

  front:
    container_name: github_actions_next
    build:
      context: ./next
      dockerfile: Dockerfile.prod
    volumes:
      - ./next:/next
    tty: true
    ports:
      - 80:80
