version: "3"

services:
  api:
    container_name: github_actions_nest
    build:
      context: ./nest
      dockerfile: Dockerfile.dev
    tty: true
    ports:
      - 3000:3000
    volumes:
      - "./nest:/nest"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    command: "yarn start:dev"

  front:
    container_name: github_actions_next
    build:
      context: ./next
      dockerfile: Dockerfile.dev
    volumes:
      - ./next:/next
    tty: true
    ports:
      - 80:80
    depends_on:
      - api
    command: "yarn dev"

  storybook:
    container_name: github_actions_storybook
    build: ./next
    volumes:
      - ./next:/next
    tty: true
    ports:
      - "6006:6006"
    environment:
      - NODE_ENV=development
    depends_on:
      - front
    command: "yarn storybook:docker"

  db:
    container_name: github_actions_mysql
    image: mysql:8.0
    volumes:
      - resson_nest-next-clud:/var/lib/mysql
      - ./db/logs:/var/log/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    ports:
      - 3306:3306
    platform: linux/x86_64

volumes:
  resson_nest-next-clud:
